export const allowedVideoExt = new Set(["mp4", "mov", "webm", "mkv", "avi"]);

export const videoMimeTypes = {
  mp4: "video/mp4",
  m4v: "video/x-m4v",
  mov: "video/quicktime",
  webm: "video/webm",
  mkv: "video/x-matroska",
  avi: "video/x-msvideo",
  wmv: "video/x-ms-wmv",
  flv: "video/x-flv",
  "3gp": "video/3gpp",
  "3g2": "video/3gpp2",
  ts: "video/mp2t",
  mts: "video/mp2t",
  ogv: "video/ogg",
  mpeg: "video/mpeg",
  mpg: "video/mpeg",
};

export const codecToExtension = {
  aac: "m4a",
  mp3: "mp3",
  opus: "opus",
  vorbis: "ogg",
  flac: "flac",
  alac: "m4a",
  pcm_s16le: "wav",
  pcm_s24le: "wav",
  pcm_s32le: "wav",
  pcm_f32le: "wav",
  ac3: "ac3",
  eac3: "eac3",
  dts: "dts",
  wmav2: "wma",
  wmapro: "wma",
  amr_nb: "amr",
  amr_wb: "amr",
  mp2: "mp2",
  truehd: "thd",
};

export const codecToMimeType = {
  aac: "audio/aac",
  mp3: "audio/mpeg",
  opus: "audio/opus",
  vorbis: "audio/ogg",
  flac: "audio/flac",
  alac: "audio/mp4",
  pcm_s16le: "audio/wav",
  pcm_s24le: "audio/wav",
  pcm_s32le: "audio/wav",
  pcm_f32le: "audio/wav",
  ac3: "audio/ac3",
  eac3: "audio/eac3",
  dts: "audio/vnd.dts",
  wmav2: "audio/x-ms-wma",
  wmapro: "audio/x-ms-wma",
  amr_nb: "audio/amr",
  amr_wb: "audio/amr-wb",
  mp2: "audio/mpeg",
  truehd: "audio/x-truehd",
};
